kie-issues#647: add writeJunitReport to invoker configuration
apache/incubator-kie-kogito-runtimes pull request #3258
Opened 2023-10-24 06:02 UTC by jstastny-cz

apache/incubator-kie-issues#647

Given that CI builds set `maven.test.failure.ignore` to true, any build failure would be silently ignored, unless invoker plugin writes the build fail as a junit report with failure outcome.

This is achieved by property writeJunitReport which is false by default and needs to be overriden.

To be validated by presence of test case `maven.invoker.it.integration-tests-springboot-kafka-it.integration-tests-springboot-kafka-it` in the test results.

2023-10-24 06:08 UTC, baldimir approved these changes

2023-10-24 10:25 UTC, jstastny-cz commented
Results in https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3258/1/testReport/maven.invoker.it/

2023-10-24 11:20 UTC, porcelli requested changes

2023-10-24 11:20 UTC, porcelli commented on kogito-build/kogito-build-no-bom-parent/pom.xml
> +	    <writeJunitReport>true</writeJunitReport>
ocd kicked here - any reason for misaligned? :)

2023-10-24 11:22 UTC, jstastny-cz commented on kogito-build/kogito-build-no-bom-parent/pom.xml
> +	    <writeJunitReport>true</writeJunitReport>
Ah, a tab jumped in! ... Thanks for noticing.

2023-10-24 11:28 UTC, jstastny-cz commented on kogito-build/kogito-build-no-bom-parent/pom.xml
> +	    <writeJunitReport>true</writeJunitReport>
Corrected the whitespace issue now.

2023-10-24 11:37 UTC, porcelli approved these changes

2023-10-24 11:54 UTC, mariofusco approved these changes

2023-10-24 12:30 UTC, jstastny-cz commented
@elguardian this will only write down the failure as a failed test case so that it's picked up by junit test results publishers.

So the builds will run the same way as they used to so far.

2023-10-24 15:38 UTC, kie-ci3 commented
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-runtimes -u https://github.com/apache/incubator-kie-kogito-runtimes/pull/3258 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3258/2/display/redirect

**Test results:**
- PASSED: 3384
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-runtimes-pr/job/PR-3258/2/testReport/org.kie.kogito.addon.quarkus.messaging.common/QuarkusEventThreadPoolTest/testQuarkusEventThreadPoolMultiThreadLongQueueTest/">org.kie.kogito.addon.quarkus.messaging.common.QuarkusEventThreadPoolTest.testQuarkusEventThreadPoolMultiThreadLongQueueTest</a></summary>
expected: not equal but was: <0>
</details>

2023-10-25 07:58 UTC, elguardian approved these changes
LGTM

2023-10-25 08:37 UTC, jstastny-cz commented
Given the nature of this fix, I am gonna merge with the one failing test:
* previously, for the first commit there was a green build
* the maven.invoker.it test results are in the jenkins job report correctly

2023-10-25 08:37 UTC, merged