[incubator-kie-issues-1131] test migration from V7 to code generation
apache/incubator-kie-kogito-runtimes pull request #3545
Opened 2024-06-04 05:06 UTC by Abhitocode

In addition to previous changes associated with PRhttps://github.com/apache/incubator-kie-kogito-runtimes/pull/3520
Migrated some BPMN processes which are being compiled using legacy v7 to code generation approach, using new branch incubator-kie-issues-1131-4

The tests can be identified by referring to Activitytest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java

Issue: https://github.com/apache/incubator-kie-issues/issues/1131

2024-06-06 14:27 UTC, elguardian commented on jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
> +        WorkflowElementIdentifier nodeId = ((WorkItemNodeInstance) nodeInstance.get()).getWorkItem().getNodeId();
you can use directly workItemHandler to retrieve the workitem instead of transverse the node instance within the process.

2024-06-06 14:28 UTC, elguardian commented on jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
> +        CallActivityMIModel model = process.createModel();
need to register the subprocess
CallActivitySubProcess

2024-06-06 14:29 UTC, elguardian requested changes
some changes required

2024-06-07 04:20 UTC, Abhitocode commented on jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
> +        CallActivityMIModel model = process.createModel();
registered in line 561

2024-06-07 09:08 UTC, elguardian commented
@Abhitocode plz rebase and fix conflicts

2024-06-11 15:55 UTC, martinweiler approved these changes

2024-06-18 09:16 UTC, merged